function PointsController(k){function p(){var a=[];if(o.length>0){for(var b=0;b<g*g;b++)a.push(o.shift());return a.reduce(function(a,b){return a.concat(b)})}else return[]}function f(){var a=[];if(l.length>0){for(var b=0;b<g*g;b++)a.push(l.shift());return a.reduce(function(a,b){return a.concat(b)})}else return[]}function h(a,b){var c=[],j=(a[0]-b[0])/10,g=(a[1]-b[1])/10;c.push([a[0],a[1]]);for(var d=0;d<10;d++)c.push([a[0]-d*j,a[1]-d*g]);c.push([b[0],b[1]]);return c}var e=k.length,g=k.length,d=function(a){for(var b=
a.length,c=[],j=0;j<b;j++)for(var d=0;d<b;d++)c.push(h(a[j],a[d]));return c}(k),o=[],l=[],j=[],v=0,c=[];this.addResponsibilityToQueue=function(a,b){o.push(d[a*e+b])};this.addAvailabilityToQueue=function(a,b){l.push(d[b*e+a])};this.addEvidenceToQueue=function(a,b){var c=[];c[0]=k[a][0];c[1]=k[a][1];c[2]=b;j.push(c)};this.getNextEvidence=function(){var a=[];if(j.length>0){for(var b=0;b<g;b++)a.push(j.shift());return a}else return[]};this.getColor=function(){return(v-1)%2==0?"red":"green"};this.getNextPath=
function(){return v%2==0?(v++,p()):(v++,f())};this.calculateExemplars=function(a,b){for(var j=a.length,d=[],g=-1*Number.MAX_VALUE,e=0;e<j;e++){var g=-1*Number.MAX_VALUE,h=[];h[0]=e;for(var f=0;f<j;f++)f==e&&this.addEvidenceToQueue(f,b[f][f]+a[f][f]),b[e][f]+a[e][f]>g&&(h[1]=f,g=b[e][f]+a[e][f],h[2]=g);d.push(h)}c.push(d)};this.getIterationExemplarResults=function(){return c.shift()};this.getPointAt=function(a){return k[a]}};function CalculateSimilarities(k){function p(f,h){return f-h}this.calculateNegativeSquaredError=function(){for(var f=k.length,h=Array(f),e=0;e<f;e++){h[e]=Array(f);for(var g=0;g<f;g++)h[e][g]=0}if(2!=k[0].length)throw"Error: this function can only be used on a 2d vector";else for(g=0;g<f;g++)for(var e=k[g],d=0;d<f;d++)h[g][d]=-1*(Math.pow(e[0]-k[d][0],2)+Math.pow(e[1]-k[d][1],2));f=h.length;e=[];for(g=0;g<f;g++)for(d=0;d<f;d++)e.push(h[g][d]);e.sort(p);d=e.length/2;g=0;d%1==0?g=e[d]:(d=Math.round(d),
g=(e[d]+e[d+1])/2);for(e=0;e<f;e++)h[e][e]=g;return h}}
function AffinityPropagation(k,p){function f(j){for(var d=Array(j),c=0;c<j;c++){d[c]=Array(j);for(var a=0;a<j;a++)d[c][a]=0}return d}function h(d){for(var e=d.length,c=Array(e),a=0;a<e;a++){c[a]=Array(e);for(var b=0;b<e;b++)c[a][b]=d[a][b]}return c}function e(d,e,c){for(var a=d.length,b=0,g=0;g<a;g++)g==c||g==e||(b+=Math.max(0,d[g][c]));return b}function g(e,g){for(var c=e.length,a=0;a<c;a++)for(var b=0;b<c;b++)e[a][b]=(1-d)*e[a][b]+d*g[a][b]}var d=0.5,o=f(k.length),l=f(k.length);this.run=function(){for(var d=
0;d<50;d++){var f=h(l),c,a=o,b=k,n=a.length==b.length?a.length:0;if(n==0)throw"The dimensions of the arrays to add are not of the same length";else{c=Array(n);for(var m=0;m<n;m++){c[m]=Array(n);for(var q=0;q<n;q++)c[m][q]=a[m][q]+b[m][q]}}a=k.length;for(b=0;b<a;b++)for(n=0;n<a;n++){var m=b,q=n,w=l[m],x=q,y=k[m][q],r,s=c,u=m,t=q;t==0?r=s[u].slice(t+1):t==s[u].length-1?r=s[u].slice(0,t):(r=s[u].slice(0,t),s=s[u].slice(t+1),r=r.concat(s));r=Math.max.apply(Math,r);w[x]=y-r;p.addResponsibilityToQueue(m,
q)}g(l,f);f=h(o);for(b=0;b<a;b++)for(n=0;n<a;n++)c=b,m=n,o[c][m]=Math.min(0,l[m][m]+e(l,c,m)),p.addAvailabilityToQueue(c,m),n==b&&(o[n][n]=e(l,n,n));g(o,f);p.calculateExemplars(l,o)}}};function DrawStaticShapes(k,p,f){var h=document.getElementById(f).getContext("2d");this.drawPointsWithLinesOnCanvas=function(e){for(var g=e.length,d=0;d<g;d++)for(var f=d+1;f<g;f++){var l=e[d],j=e[f];h.beginPath();h.moveTo(l[0],l[1]);h.lineTo(j[0],j[1]);h.strokeStyle=p;h.stroke()}g=e.length;for(d=0;d<g;d++)f=e[d][0],l=e[d][1],h.beginPath(),h.arc(f,l,10,0,Math.PI*2,!0),h.fillStyle=k,h.fill()}}
function DrawMovingParticles(k,p,f){var h=[],e=0,g=0,d=0,o=document.getElementById(p).getContext("2d"),l=document.getElementById("canvas3").getContext("2d");this.draw=function(){if(e==g){h=f.getNextPath();e=h.length;g=0;if(d==2){l.clearRect(0,0,800,600);for(var j=f.getIterationExemplarResults(),k=j.length,c=0;c<k;c++){var a=j[c][1],b=f.getPointAt(j[c][0]),a=f.getPointAt(a);l.beginPath();l.moveTo(b[0],b[1]);l.lineTo(a[0],a[1]);l.strokeStyle="black";l.stroke()}j=f.getNextEvidence();b=[];for(c=0;c<k;c++)j[c][2]=
j[c][2]<0?0:j[c][2],b.push(j[c][2]);b=Math.max.apply(Math,b);b=b<=0?1:b;for(c=0;c<k;c++)console.log(j[c][2]+", "+b),j[c][2]/=b;for(c=0;c<k;c++){var b=j[c][2]>0?Math.round(255*(1-j[c][2])):255,a=j[c][0],n=j[c][1],m=b;l.beginPath();l.arc(a,n,11,0,Math.PI*2,!0);l.fillStyle="rgba("+m+","+m+",255, 0.5)";l.strokeStyle="rgba("+m+","+m+",255, 0.5)";l.fill();}d=0}d++}else k=h[g][0],c=h[g][1],o.clearRect(0,0,800,600),o.beginPath(),o.arc(k,c,5,0,Math.PI*2,!0),o.fillStyle=f.getColor(),
o.fill(),g++}};var points=[[12,12],[250,40],[200,200],[388,288],[100,30],[50,50],[20,250],[340,120],[300,200],[340,80],[40,288],[50,140],[100,200]],canvas=document.getElementById("canvasLegend"),context=canvas.getContext("2d"),betterThanBlack="#444";context.font="bold 18px Helvetica neue";context.textBaseline="top";context.fillStyle=betterThanBlack;context.fillText("Legend:",35,7);context.font="normal 16px Helvetica neue";
function drawCircle(k,p,f,h){context.beginPath();context.arc(k,p,f,0,Math.PI*2,!0);context.fillStyle=h;context.fill()}drawCircle(127,20,6,"red");context.fillStyle=betterThanBlack;context.fillText("Responsibility",142,10);drawCircle(280,20,6,"green");context.fillStyle=betterThanBlack;context.fillText("Availability",295,10);for(var i=0;i<10;i++)circleColor="rgba("+i*25+","+i*25+",255, 0.5)",drawCircle(500+i*15,20,10,betterThanBlack),drawCircle(500+i*15,20,11,circleColor);context.fillStyle=betterThanBlack;
context.fillText("Exemplar",410,10);context.fillStyle=betterThanBlack;context.fillText("Non-Exemplar",655,10);var pointsController=new PointsController(points),calcSim=new CalculateSimilarities(points),simMatrix=calcSim.calculateNegativeSquaredError(),ap=new AffinityPropagation(simMatrix,pointsController);ap.run();var drawStaticShapes=new DrawStaticShapes("black","#eee","canvas");drawStaticShapes.drawPointsWithLinesOnCanvas(points);
var drawMovingParticles=new DrawMovingParticles("blue","canvas2",pointsController);setInterval(drawMovingParticles.draw,10);
